backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "post"
    label: "Post"
    folder: "src/content/post"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Tag", name: "tags", widget: "list", default: [] }
      - { label: "Contenuto", name: "body", widget: "markdown" }

  - name: "recensioni"
    label: "Recensioni"
    folder: "src/content/recensioni"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Tag", name: "tags", widget: "list", default: [] }
      - { label: "Contenuto", name: "body", widget: "markdown" }

  - name: "schede-tecniche"
    label: "Schede Tecniche"
    folder: "src/content/schede-tecniche"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Tag", name: "tags", widget: "list", default: [] }
      - { label: "Contenuto", name: "body", widget: "markdown" }

  - name: "tutorial"
    label: "Tutorial"
    folder: "src/content/tutorial"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Tag", name: "tags", widget: "list", default: [] }
      - { label: "Contenuto", name: "body", widget: "markdown" }
